In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr = np.array([3.7, -1.2, -2.6, 0,5,12,9,10,11])
arr

array([ 3.7, -1.2, -2.6,  0. ,  5. , 12. ,  9. , 10. , 11. ])

In [3]:
numeric_string = np.array(['1.25', '-9.6', '4.2'], dtype=np.string_)
numeric_string.astype(float) #string형태의 자료를 float형태로 바꾸기

array([ 1.25, -9.6 ,  4.2 ])

In [4]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)   #[]안에서 0.45를 .45로 표현된것을 다시 바꾸는 기능
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [6]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0,          0], dtype=uint32)

In [8]:
arr=np.array([[1., 2., 3.], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
arr*arr  #같은자리끼리

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
arr-arr  #같은자리끼리

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
1 / arr  #같은자리끼리

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [12]:
arr ** 0.5  #루트씌우기

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [13]:
arr2 = np.array([[0., 4., 1.], [7., 9., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  9., 12.]])

In [14]:
#크다, 작다
arr2 > arr   #각 자리의 값끼리 비교
#나중에 True값만 뽑아내는 방식으로 활용 가능

array([[False,  True, False],
       [ True,  True,  True]])

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#특정 몇번째의 값 가져오기
arr[5] 

5

In [17]:
#split
arr[5:9]

array([5, 6, 7, 8])

In [18]:
#특정위치에 다른 값 넣기
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [19]:
arr_slice = arr[5:9]
arr_slice

array([12, 12, 12, 12])

In [20]:
arr_slice[1]=12345
arr_slice

array([   12, 12345,    12,    12])

In [21]:
arr
#달라져있어.....array리스트는 속도향상을 위해서 원본의 내용이 달라짐 

array([    0,     1,     2,     3,     4,    12, 12345,    12,    12,
           9])

In [22]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64, 64])

In [23]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64, 64,  9])

In [24]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[2]   #2번째 행을 가져오기

array([7, 8, 9])

In [26]:
arr2d[0][2]  #0번째 행의 2번째 열

3

In [27]:
arr2d[0,2]   #0번째 행의 2번째 열 값

3

In [28]:
arr3d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3d[0,0]

array([1, 2, 3])

In [31]:
arr3d[0,0,1]

2

In [32]:
old_values = arr3d[0].copy()
old_values
#직접고치는것이 아니라 일부를 복사해두고 싶을때 사용하는 기능
#원본데이터를 바로 고쳤을때 발생할 리스크를 줄이기 위해서

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
#다시되돌리기
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[1,0]

array([7, 8, 9])

In [36]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64, 64,  9])

In [38]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [39]:
arr2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[:2]  #0~1까지

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#[2,3] [5,6]을 출력하고 싶을 때
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [42]:
#[4,5],[7,8]을 출력하고 싶을 때
arr2d[1:, 0:2]

array([[4, 5],
       [7, 8]])

In [43]:
#[4,5]을 출력하고 싶을때
arr2d[1,0:2]

array([4, 5])

In [44]:
#[3],[6]을 출력하고 싶을때
arr2d[:2,2:]

array([[3],
       [6]])

In [45]:
arr2d[:2,2]

array([3, 6])

In [46]:
#[5],[8]을 출력하고싶을때
arr2d[1:,1:2]

array([[5],
       [8]])

In [47]:
#[1],[4],[7]을 출력하고 싶을 때
arr2d[:,0:1]

array([[1],
       [4],
       [7]])

In [48]:
#[2,3] [5,6]에 다른값(0) 추가
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
#T/F로 인덱스처리하기

In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names
                  

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
data = np.random.randn(7,4)
data

array([[ 0.73808826, -0.05289313, -0.85187947, -0.24779059],
       [-0.26615011, -0.01471312,  1.52368449, -0.08452157],
       [-0.80300427, -0.86898607,  1.00485934, -0.22142659],
       [ 0.04542414,  0.56006781, -0.36674573, -0.81747744],
       [ 0.81220605, -0.85410761,  0.63875841, -0.84668853],
       [-0.09786461,  0.40807975,  1.05523028, -0.30336874],
       [ 1.30254269,  0.9726089 ,  0.32685308,  0.51840566]])

In [51]:
######end