Numpy 예제 1

In [1]:
#numpy에서는 모든걸 숫자로 다룹니다.
import numpy as np

In [2]:
np.random.seed() #재연성이 가능하게 하는 기능, ()안에 있는 값을 기준으로

In [3]:
import matplotlib.pyplot as plt

In [4]:
plt.rc('figure', figsize=(10,6)) #resource / 그림을 그려줄때 가로10 세로 6 / 그림의 사이즈 설정

In [6]:
np.set_printoptions(precision=4, suppress=True) #소수점 4자리

In [14]:
#두개가 같은 내용 다른방식

my_arr = np.arange(1000000)  #numpy방식
%time for _ in range(10): my_arr2 = my_arr*2  
# '%time'은 그 한줄 코드를 실행하는데 걸린 시간을 알 수 있는 함수, my_arr에 2를 곱한것
#  _  은 해당 값이 필요하지 않거나 사용되지 않는 값을 _에 할당하기만 하면된다.

Wall time: 54 ms


In [15]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x*2 for x in my_list] #my_list에 2를 곱한 것

Wall time: 1.77 s


In [ ]:
#numpy 방식이 코드도 더 짧고 속도도 더 빠른것을 알 수 있음

In [10]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [11]:
my_arr2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [12]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [13]:
my_list2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
#ndarray =여러차원의 array

In [16]:
data = np.random.randn(2,3)  #2X3의 행렬로 난수를 발생시켜라
data

array([[ 0.5989,  0.6558,  0.0204],
       [ 0.7167,  0.2126, -2.0298]])

In [17]:
data*10


array([[  5.9889,   6.5585,   0.2036],
       [  7.1668,   2.1257, -20.298 ]])

In [18]:
data

array([[ 0.5989,  0.6558,  0.0204],
       [ 0.7167,  0.2126, -2.0298]])

In [19]:
data+data  
#같은자리에 있는 난수끼리 더해주는 것

array([[ 1.1978,  1.3117,  0.0407],
       [ 1.4334,  0.4251, -4.0596]])

In [20]:
data 
#그래도 원본은 수정이 되지 않음

array([[ 0.5989,  0.6558,  0.0204],
       [ 0.7167,  0.2126, -2.0298]])

In [21]:
data.shape  
#해당 데이터의 형태를 알고 싶을 때 = shape

(2, 3)

In [22]:
data.dtype  #데이터 타입, 디폴트값 float64

dtype('float64')

In [23]:
data1 = [6, 7.53, 8, 0,1] #정수와 실수가 섞여있음, 그대로 출력가능
data1

[6, 7.53, 8, 0, 1]

In [24]:
arr = np.array(data1)   #numpy의 array로 바꿀 때 ->속도를 위해서 바꿔주는것
arr   
#numpy로 바뀌면서 자동으로 다 실수로(7.53을 기준으로) 바꿔준거야

#주의사항 : numpy의 array는 같은 자료형만 넣어야 가능 

array([6.  , 7.53, 8.  , 0.  , 1.  ])

In [25]:
data4 = [[1,2,3,4],[5,6,7,8]]  #2행 4열짜리 리스트 , 2차원 리스트
data4

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [26]:
arr3 = np.array(data4)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr3.ndim  
#몇차원인지알아보기

2

In [28]:
arr3.shape  
#행렬이 어떤 형태인지

(2, 4)

In [29]:
arr3.dtype

dtype('int32')

In [30]:
np.zeros(10)  
#전부다 제로인 것을 열개 만들어라 , 1차원으로 만들고 싶으면 개수만 ()안에 입력
#기본값이 실수라서 아래와 같이 출력됨

#np.ones(__) 은 전부 1인 것으로 __개를 만들어라

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,6)) #3행 6열로 만들겠다

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((2,2,2)) #3차원으로 만들겠다

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [33]:
np.empty((2,3,2))  #일종의 난수이지만 정확히말하자면 무작위값


# 배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 
# np.empty()  = 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 명령어  
# empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
#자료형을 지정하고싶을때
arr1 = np.array([1,2,3], dtype=np.float64)    #특정 자료형으로 설정하고 싶을 때, 실제 입력한 자료는 정수이지만[1,2,3] 실수형태로 만들어짐
arr1

array([1., 2., 3.])

In [36]:
arr2 = np.array([1,2,3], dtype=np.int32) #실제 입력한 자료는 정수이긴하지만 자료형태를 정수로 고정시킴
arr2

array([1, 2, 3])

In [37]:
float_arr2 = arr2.astype(np.float64) #내가 원하는 형태 (float64)로 바꾸는 기능

#자료형을 처음부터 정해줄 수도 있지만 중간에도 수정이 가능하다는 것
arr2

array([1, 2, 3])

In [38]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('float64')

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0,5,12,9,10,11])
arr

array([ 3.7, -1.2, -2.6,  0. ,  5. , 12. ,  9. , 10. , 11. ])

In [ ]:
######end